### ISSUE TITLE
Allow multiple BGP community strings as target for "BGP Community" query type

### ISSUE THREAD

**Issue by syntax-terr0r** [thatmattlove/hyperglass#142]
# Feature Description

The "BGP Community" query type allows only one community string as the target at the moment.
Allowing multiple communities would allow for more granular queries.

# Environment & Use Case

We operate a global network primarily on Juniper devices and want to use hyperglass to make routing information within our network available to people and teams that do not have direct access to the devices.

Consider the following use case:

A transit provider sends us a full table. The provider tags prefixes with communities based on the region ($comm-region-X) they were received in as well as the info if it was received from an internal peer ($comm-internal), a direct customer ($comm-customer) of theirs, or another transit provider ($comm-external).

If we want to know which prefixes that we receive from that provider are originating from direct customers in Germany for example, we need to include two BGP communities in that query: $comm-region-germany + $comm-customer

# Additional Context

Querying multiple community targets can already be done with the customizing options we have but unfortunately not for the structured output.

We have it working for the plaintext output with changing the validation regex for the extended communities to
`extended_as: '^[0-9]{0,5}\:[0-9]{1,5}(?: [0-9]{0,5}\:[0-9]{1,5})*$'`
which matches either a single extended community `1234:999` or multiple communities separated by a space `1234:999 5678:999`

Then, changing the command for the BGP community query from
`"show route protocol bgp table inet.0 community {target}"`
to
`"show route protocol bgp table inet.0 community [ {target} ]"`
makes the query work on the devices. The square bracket notation also works with a single community string.

However, since the API is the primary interface through which other teams would interact with hyperglass, having this working with the structured output would be desired.

**Comment by checktheroads** [comment]
Hello, I think this is a good idea. However, I'm marking this as blocked due to #110, which is going to change the way commands are implemented as a whole, so I'd rather not but a bunch of work into this request just to have to redo it anyway.

Thanks!

**Comment by syntax-terr0r** [comment]
Sounds good, thanks!
