### ISSUE TITLE
Replace hyperglass-agent with generic HTTP transport support

### ISSUE THREAD

**Issue by thatmattlove** [thatmattlove/hyperglass#143]
[hyperglass-agent](https://github.com/checktheroads/hyperglass-agent) will be deprecated and replaced with the ability to query HTTP targets for data. It's likely that I'll write a small, simple utility to replace what hyperglass-agent does under the hood (run shell commands triggered by HTTP request), but said utility will not be integrated with hyperglass in any way. In fact, one could accomplish the same thing with [Caddy using the `exec` module](https://caddyserver.com/docs/modules/exec).

**Comment by checktheroads** [comment]
After reviewing how this should be implemented, I'm marking it as blocked by #110.

**Comment by thatmattlove** [comment]
This has been implemented in v2.0.0, which is currently in the final stages of development.
