### ISSUE TITLE
Use sudo if possible for bird_ssh platform to execute Bird CLI queries

### ISSUE THREAD

**Issue by samip5** [thatmattlove/hyperglass#144]
# Feature Description

I would like to see bird_ssh platfrom to try to use sudo first, before failing back to using birdc commands directly with the provided credentials.

### Is your feature request related to a problem? Please describe.

Related to the fact that you need to provide root credentials for Bird cli access

# Environment & Use Case

Device type: EdgeRouter with Bird
Use case: Not wanting to provide root credentials directly, but to only allow birdc specifc commands via sudo configuration.

**Comment by checktheroads** [comment]
This would require a significant overhaul to the entirety of command execution logic. We would need to begin checking every response for platform-specific errors or output to indicate that a command failed but is eligible for retry during the same session. In my opinion, a better solution would be to simply [override](https://hyperglass.io/docs/commands) the `bird_ssh` commands to use `sudo`, or not, depending on the node's capabilities and/or configuration.

I'll leave this open for a little while for other users to comment.
