### ISSUE TITLE
hyperglass build-ui fails without error

### ISSUE THREAD

**Issue by GrandArcher** [thatmattlove/hyperglass#154]
hyperglass build-ui fails without error

# Bug Description

untangledtech@lg:~/hyperglass$ hyperglass build-ui
[WARNING] 20210726 16:55:17 | hyperglass.models.config.vrf:239 | set_dynamic → You have set the VRF name to 'default'. This is no longer the way to
designate a VRF as the default (or global routing table) VRF. Instead,
add 'default: true' to the VRF definition.

[INFO] 20210726 16:55:17 | hyperglass.configuration.main:39 | <module> → Configuration directory: /home/untangledtech/hyperglass
[WARNING] 20210726 16:55:17 | hyperglass.configuration.main:65 | _check_config_files → '/home/untangledtech/hyperglass/hyperglass.yaml' was not found, but is not required to run hyperglass. Defaults will be used.
[WARNING] 20210726 16:55:17 | hyperglass.configuration.main:65 | _check_config_files → '/home/untangledtech/hyperglass/commands.yaml' was not found, but is not required to run hyperglass. Defaults will be used.
[DEBUG] 20210726 16:55:17 | hyperglass.log:75 | set_log_level → Debugging enabled
[DEBUG] 20210726 16:55:17 | hyperglass.configuration.main:119 | <module> → Unvalidated configuration from None: {}
[DEBUG] 20210726 16:55:17 | hyperglass.configuration.main:132 | <module> → Unvalidated commands from None: {}
[DEBUG] 20210726 16:55:17 | hyperglass.configuration.main:137 | <module> → Unvalidated devices from /home/untangledtech/hyperglass/devices.yaml: {'routers': [{'name': 'NEOIX', 'address': '10.72.0.11', 'network': {'name': 'production', 'display_name': 'RouteReflector1'}, 'credential': {'username': 'Uselessness', 'password': 'Uselessness'}, 'port': 22, 'nos': 'bird', 'vrfs': [{'name': 'global', 'default': True, 'ipv4': {'source_address': '172.82.25.4'}, 'ipv6': None}]}]}
[DEBUG] 20210726 16:55:17 | hyperglass.log:118 | enable_file_logging → Logging to /tmp/hyperglass.log enabled
Starting new UI build with a 180 second timeout...
[DEBUG] 20210726 16:55:17 | hyperglass.util.frontend:77 | read_package_json → package.json:
{'name': 'ui', 'version': '1.0.0', 'description': 'UI for hyperglass, the modern network looking glass', 'author': 'Matt Love', 'license': 'BSD-3-Clause-Clear', 'private': True, 'scripts': {'lint': 'eslint . --ext .ts --ext .tsx', 'dev': 'node nextdev', 'start': 'next start', 'typecheck': 'tsc --noEmit', 'format': 'prettier -c .', 'clean': 'rimraf --no-glob ./.next ./out', 'check:es:export': "es-check es5 './out/**/*.js' -v", 'check:es:build': "es-check es5 './.next/static/**/*.js' -v", 'build': 'next build && next export -o ../hyperglass/static/ui'}, 'browserslist': '> 0.25%, not dead', 'dependencies': {'@chakra-ui/react': '^1.6.3', '@emotion/react': '^11.4.0', '@emotion/styled': '^11.3.0', '@hookform/devtools': '^3.1.0', '@hookform/resolvers': '^2.5.1', '@hookstate/core': '^3.0.7', '@hookstate/persistence': '^3.0.0', '@meronex/icons': '^4.0.0', 'dagre': '^0.8.5', 'dayjs': '^1.10.4', 'framer-motion': '^4.1.17', 'lodash': '^4.17.21', 'next': '^10.2.3', 'palette-by-numbers': '^0.1.5', 'react': '^17.0.2', 'react-countdown': '^2.2.1', 'react-device-detect': '^1.15.0', 'react-dom': '^17.0.2', 'react-fast-compare': '^3.2.0', 'react-flow-renderer': '^9.6.0', 'react-ga': '^3.3.0', 'react-hook-form': '^7.7.0', 'react-markdown': '^5.0.3', 'react-query': '^3.16.0', 'react-select': '^4.3.1', 'react-table': '^7.7.0', 'remark-gfm': '^1.0.0', 'string-format': '^2.0.0', 'vest': '^3.2.3'}, 'devDependencies': {'@hookstate/devtools': '^3.0.0', '@types/dagre': '^0.7.44', '@types/node': '^14.14.41', '@types/react': '^17.0.3', '@types/react-select': '^4.0.15', '@types/react-table': '^7.7.1', '@types/string-format': '^2.0.0', '@typescript-eslint/eslint-plugin': '^4.11.1', '@typescript-eslint/parser': '^4.11.1', '@upstatement/eslint-config': '^0.4.3', '@upstatement/prettier-config': '^0.3.0', 'babel-eslint': '^10.1.0', 'eslint': '^6.8.0', 'eslint-config-prettier': '^7.1.0', 'eslint-config-react-app': '^5.2.0', 'eslint-import-resolver-typescript': '^2.3.0', 'eslint-plugin-import': '^2.22.1', 'eslint-plugin-jest': '^24.1.3', 'eslint-plugin-json': '^2.1.2', 'eslint-plugin-jsx-a11y': '^6.2.3', 'eslint-plugin-prettier': '^3.3.0', 'eslint-plugin-react': '^7.22.0', 'eslint-plugin-react-hooks': '^4.2.0', 'express': '^4.17.1', 'http-proxy-middleware': '0.20.0', 'onchange': '^7.1.0', 'prettier': '^2.2.1', 'prettier-eslint': '^12.0.0', 'typescript': '^4.3.2'}}
[DEBUG] 20210726 16:55:17 | hyperglass.util.frontend:311 | build_frontend → node_modules has not been initialized. Starting initialization...

❌ Error building UI:
untangledtech@lg:~/hyperglass$

# Expected behavior

## Local Configurations

`routers:
 - name: NEOIX
   address: 10.72.0.11
   network:
     name: production
     display_name: RouteReflector1
   credential:
     username: uselessness
     password: uselessness
   port: 22
   nos: bird
   vrfs:
     - name: global
       default: true
       ipv4:
         source_address: 172.82.25.4
       ipv6: null
`

# Environment
VM
Distributor ID: Ubuntu
Description:    Ubuntu 20.04.2 LTS
Release:        20.04
Codename:       focal

## Server
| Metric | Value |
| :----- | :---- |
| **hyperglass Version** | 1.0.4 |
| **hyperglass Path** | `/home/untangledtech/hyperglass` |
| **Python Version** | `3.8.10` |
| **Node Version** | `14.17.2` |
| **Platform Info** | `Linux-5.4.0-80-generic-x86_64-with-glibc2.29` |
| **CPU Info** | Intel(R) Atom(TM) CPU  C2758  @ 2.41GHz |
| **Logical Cores** | `2` |
| **Physical Cores** | `2` |
| **Processor Speed** | `2.416666GHz` |
| **Total Memory** | 1.03 GB |
| **Memory Utilization** | 39.4% |
| **Total Disk Space** | 16.84 GB |
| **Disk Utilization** | 46.8% |

**Comment by GrandArcher** [comment]
After running 'hyperglass clear-cache' and rerunning 'hyperglass build-ui' I get this.

untangledtech@lg:~$ hyperglass build-ui
[WARNING] 20210726 17:41:26 | hyperglass.models.config.vrf:239 | set_dynamic → You have set the VRF name to 'default'. This is no longer the way to
designate a VRF as the default (or global routing table) VRF. Instead,
add 'default: true' to the VRF definition.

[INFO] 20210726 17:41:26 | hyperglass.configuration.main:39 | <module> → Configuration directory: /home/untangledtech/hyperglass
[WARNING] 20210726 17:41:26 | hyperglass.configuration.main:65 | _check_config_files → '/home/untangledtech/hyperglass/hyperglass.yaml' was not found, but is not required to run hyperglass. Defaults will be used.
[WARNING] 20210726 17:41:26 | hyperglass.configuration.main:65 | _check_config_files → '/home/untangledtech/hyperglass/commands.yaml' was not found, but is not required to run hyperglass. Defaults will be used.
[DEBUG] 20210726 17:41:26 | hyperglass.log:75 | set_log_level → Debugging enabled
[DEBUG] 20210726 17:41:26 | hyperglass.configuration.main:119 | <module> → Unvalidated configuration from None: {}
[DEBUG] 20210726 17:41:26 | hyperglass.configuration.main:132 | <module> → Unvalidated commands from None: {}
[DEBUG] 20210726 17:41:26 | hyperglass.configuration.main:137 | <module> → Unvalidated devices from /home/untangledtech/hyperglass/devices.yaml: {'routers': [{'name': 'NEOIX', 'address': '10.72.0.11', 'network': {'name': 'production', 'display_name': 'RouteReflector1'}, 'credential': {'username': 'uselessness', 'password': 'Uselessness'}, 'port': 22, 'nos': 'bird', 'vrfs': [{'name': 'global', 'default': True, 'ipv4': {'source_address': '172.82.25.4'}, 'ipv6': None}]}]}
[DEBUG] 20210726 17:41:26 | hyperglass.log:118 | enable_file_logging → Logging to /tmp/hyperglass.log enabled
Starting new UI build with a 180 second timeout...
[DEBUG] 20210726 17:41:26 | hyperglass.util.frontend:77 | read_package_json → package.json:
{'name': 'ui', 'version': '1.0.0', 'description': 'UI for hyperglass, the modern network looking glass', 'author': 'Matt Love', 'license': 'BSD-3-Clause-Clear', 'private': True, 'scripts': {'lint': 'eslint . --ext .ts --ext .tsx', 'dev': 'node nextdev', 'start': 'next start', 'typecheck': 'tsc --noEmit', 'format': 'prettier -c .', 'clean': 'rimraf --no-glob ./.next ./out', 'check:es:export': "es-check es5 './out/**/*.js' -v", 'check:es:build': "es-check es5 './.next/static/**/*.js' -v", 'build': 'next build && next export -o ../hyperglass/static/ui'}, 'browserslist': '> 0.25%, not dead', 'dependencies': {'@chakra-ui/react': '^1.6.3', '@emotion/react': '^11.4.0', '@emotion/styled': '^11.3.0', '@hookform/devtools': '^3.1.0', '@hookform/resolvers': '^2.5.1', '@hookstate/core': '^3.0.7', '@hookstate/persistence': '^3.0.0', '@meronex/icons': '^4.0.0', 'dagre': '^0.8.5', 'dayjs': '^1.10.4', 'framer-motion': '^4.1.17', 'lodash': '^4.17.21', 'next': '^10.2.3', 'palette-by-numbers': '^0.1.5', 'react': '^17.0.2', 'react-countdown': '^2.2.1', 'react-device-detect': '^1.15.0', 'react-dom': '^17.0.2', 'react-fast-compare': '^3.2.0', 'react-flow-renderer': '^9.6.0', 'react-ga': '^3.3.0', 'react-hook-form': '^7.7.0', 'react-markdown': '^5.0.3', 'react-query': '^3.16.0', 'react-select': '^4.3.1', 'react-table': '^7.7.0', 'remark-gfm': '^1.0.0', 'string-format': '^2.0.0', 'vest': '^3.2.3'}, 'devDependencies': {'@hookstate/devtools': '^3.0.0', '@types/dagre': '^0.7.44', '@types/node': '^14.14.41', '@types/react': '^17.0.3', '@types/react-select': '^4.0.15', '@types/react-table': '^7.7.1', '@types/string-format': '^2.0.0', '@typescript-eslint/eslint-plugin': '^4.11.1', '@typescript-eslint/parser': '^4.11.1', '@upstatement/eslint-config': '^0.4.3', '@upstatement/prettier-config': '^0.3.0', 'babel-eslint': '^10.1.0', 'eslint': '^6.8.0', 'eslint-config-prettier': '^7.1.0', 'eslint-config-react-app': '^5.2.0', 'eslint-import-resolver-typescript': '^2.3.0', 'eslint-plugin-import': '^2.22.1', 'eslint-plugin-jest': '^24.1.3', 'eslint-plugin-json': '^2.1.2', 'eslint-plugin-jsx-a11y': '^6.2.3', 'eslint-plugin-prettier': '^3.3.0', 'eslint-plugin-react': '^7.22.0', 'eslint-plugin-react-hooks': '^4.2.0', 'express': '^4.17.1', 'http-proxy-middleware': '0.20.0', 'onchange': '^7.1.0', 'prettier': '^2.2.1', 'prettier-eslint': '^12.0.0', 'typescript': '^4.3.2'}}
[DEBUG] 20210726 17:41:26 | hyperglass.util.frontend:308 | build_frontend → node_modules is already initialized
colinear!
colinear!
x_order_2: colinear!
x_order_2: colinear!
x_order_2: colinear!
x_order_2: colinear!
x_order_2: colinear!
x_order_2: colinear!
x_order_2: colinear!
x_order_2: colinear!
x_order_2: colinear!
x_order_2: colinear!
x_order_2: colinear!
x_order_2: colinear!
x_order_2: colinear!
x_order_2: colinear!
x_order_2: colinear!
x_order_2: colinear!
x_order_2: colinear!
x_order_2: colinear!
x_order_2: colinear!
x_order_2: colinear!
x_order_2: colinear!
x_order_2: colinear!
x_order_2: colinear!
x_order_2: colinear!
x_order_2: colinear!
colinear!
colinear!
x_order_2: colinear!
x_order_2: colinear!
x_order_2: colinear!
x_order_2: colinear!
colinear!
colinear!
x_order_2: colinear!
x_order_2: colinear!
x_order_2: colinear!
x_order_2: colinear!
colinear!
colinear!
x_order_2: colinear!
x_order_2: colinear!
x_order_2: colinear!
colinear!
colinear!
x_order_2: colinear!
x_order_2: colinear!
colinear!
colinear!
x_order_2: colinear!
x_order_2: colinear!
x_order_2: colinear!
x_order_2: colinear!
x_order_2: colinear!
x_order_2: colinear!
x_order_2: colinear!
x_order_2: colinear!
x_order_2: colinear!
x_order_2: colinear!
x_order_2: colinear!
x_order_2: colinear!
colinear!
colinear!
colinear!
colinear!
x_order_2: colinear!
x_order_2: colinear!
x_order_2: colinear!
x_order_2: colinear!
x_order_2: colinear!
x_order_2: colinear!
x_order_2: colinear!
x_order_2: colinear!
x_order_2: colinear!
x_order_2: colinear!
x_order_2: colinear!
x_order_2: colinear!
x_order_2: colinear!
x_order_2: colinear!
x_order_2: colinear!
x_order_2: colinear!
x_order_2: colinear!
x_order_2: colinear!
x_order_2: colinear!
x_order_2: colinear!
x_order_2: colinear!
x_order_2: colinear!
x_order_2: colinear!
x_order_2: colinear!
x_order_2: colinear!
x_order_2: colinear!
x_order_2: colinear!
x_order_2: colinear!
x_order_2: colinear!
x_order_2: colinear!
x_order_2: colinear!
x_order_2: colinear!
x_order_2: colinear!
x_order_2: colinear!
x_order_2: colinear!
x_order_2: colinear!
x_order_2: colinear!
x_order_2: colinear!
x_order_2: colinear!
x_order_2: colinear!
x_order_2: colinear!
x_order_2: colinear!
x_order_2: colinear!
x_order_2: colinear!
x_order_2: colinear!
x_order_2: colinear!
x_order_2: colinear!
x_order_2: colinear!
x_order_2: colinear!
x_order_2: colinear!
x_order_2: colinear!
x_order_2: colinear!
x_order_2: colinear!
x_order_2: colinear!
x_order_2: colinear!
x_order_2: colinear!
x_order_2: colinear!
x_order_2: colinear!
x_order_2: colinear!
x_order_2: colinear!
x_order_2: colinear!
x_order_2: colinear!
x_order_2: colinear!
x_order_2: colinear!
x_order_2: colinear!
x_order_2: colinear!
x_order_2: colinear!
x_order_2: colinear!
x_order_2: colinear!
x_order_2: colinear!
x_order_2: colinear!
x_order_2: colinear!
x_order_2: colinear!
[DEBUG] 20210726 17:41:28 | hyperglass.util.frontend:330 | build_frontend → Generated 21 favicons
[INFO] 20210726 17:41:28 | hyperglass.util.frontend:362 | build_frontend → Starting UI build...
[DEBUG] 20210726 17:41:28 | hyperglass.util.frontend:363 | build_frontend → Created temporary UI config file: '/tmp/hyperglass_1yxxwsgk.json' for build 9260897f03965ec8d872af5a216b744b8f526f818ba17f18b3be84e78f2efe56
[ERROR] 20210726 17:47:42 | hyperglass.util.frontend:157 | build_ui →
Messages:
info  - Using webpack 5. Reason: future.webpack5 option enabled https://nextjs.org/docs/messages/webpack5
info  - Checking validity of types...
info  - Creating an optimized production build...
Errors:
<--- Last few GCs --->

[1250:0x60b89c0]   367128 ms: Scavenge (reduce) 982.8 (998.3) -> 982.1 (998.3) MB, 5.8 / 0.0 ms  (average mu = 0.165, current mu = 0.038) allocation failure
[1250:0x60b89c0]   367171 ms: Scavenge (reduce) 983.0 (995.3) -> 982.4 (996.3) MB, 6.1 / 0.0 ms  (average mu = 0.165, current mu = 0.038) allocation failure
[1250:0x60b89c0]   367205 ms: Scavenge (reduce) 983.1 (995.3) -> 982.6 (996.6) MB, 7.2 / 0.0 ms  (average mu = 0.165, current mu = 0.038) allocation failure


<--- JS stacktrace --->

FATAL ERROR: Ineffective mark-compacts near heap limit Allocation failed - JavaScript heap out of memory
 1: 0xa24ed0 node::Abort() [node]
 2: 0x966115 node::FatalError(char const*, char const*) [node]
 3: 0xb9acde v8::Utils::ReportOOMFailure(v8::internal::Isolate*, char const*, bool) [node]
 4: 0xb9b057 v8::internal::V8::FatalProcessOutOfMemory(v8::internal::Isolate*, char const*, bool) [node]
 5: 0xd56ea5  [node]
 6: 0xd57a2f  [node]
 7: 0xd65abb v8::internal::Heap::CollectGarbage(v8::internal::AllocationSpace, v8::internal::GarbageCollectionReason, v8::GCCallbackFlags) [node]
 8: 0xd6967c v8::internal::Heap::AllocateRawWithRetryOrFailSlowPath(int, v8::internal::AllocationType, v8::internal::AllocationOrigin, v8::internal::AllocationAlignment) [node]
 9: 0xd37d2b v8::internal::Factory::NewFillerObject(int, bool, v8::internal::AllocationType, v8::internal::AllocationOrigin) [node]
10: 0x108035f v8::internal::Runtime_AllocateInYoungGeneration(int, unsigned long*, v8::internal::Isolate*) [node]
11: 0x1427079  [node]
Aborted (core dumped)
[ERROR] 20210726 17:47:42 | hyperglass.util.frontend:401 | build_frontend →
Messages:
info  - Using webpack 5. Reason: future.webpack5 option enabled https://nextjs.org/docs/messages/webpack5
info  - Checking validity of types...
info  - Creating an optimized production build...
Errors:
<--- Last few GCs --->

[1250:0x60b89c0]   367128 ms: Scavenge (reduce) 982.8 (998.3) -> 982.1 (998.3) MB, 5.8 / 0.0 ms  (average mu = 0.165, current mu = 0.038) allocation failure
[1250:0x60b89c0]   367171 ms: Scavenge (reduce) 983.0 (995.3) -> 982.4 (996.3) MB, 6.1 / 0.0 ms  (average mu = 0.165, current mu = 0.038) allocation failure
[1250:0x60b89c0]   367205 ms: Scavenge (reduce) 983.1 (995.3) -> 982.6 (996.6) MB, 7.2 / 0.0 ms  (average mu = 0.165, current mu = 0.038) allocation failure


<--- JS stacktrace --->

FATAL ERROR: Ineffective mark-compacts near heap limit Allocation failed - JavaScript heap out of memory
 1: 0xa24ed0 node::Abort() [node]
 2: 0x966115 node::FatalError(char const*, char const*) [node]
 3: 0xb9acde v8::Utils::ReportOOMFailure(v8::internal::Isolate*, char const*, bool) [node]
 4: 0xb9b057 v8::internal::V8::FatalProcessOutOfMemory(v8::internal::Isolate*, char const*, bool) [node]
 5: 0xd56ea5  [node]
 6: 0xd57a2f  [node]
 7: 0xd65abb v8::internal::Heap::CollectGarbage(v8::internal::AllocationSpace, v8::internal::GarbageCollectionReason, v8::GCCallbackFlags) [node]
 8: 0xd6967c v8::internal::Heap::AllocateRawWithRetryOrFailSlowPath(int, v8::internal::AllocationType, v8::internal::AllocationOrigin, v8::internal::AllocationAlignment) [node]
 9: 0xd37d2b v8::internal::Factory::NewFillerObject(int, bool, v8::internal::AllocationType, v8::internal::AllocationOrigin) [node]
10: 0x108035f v8::internal::Runtime_AllocateInYoungGeneration(int, unsigned long*, v8::internal::Isolate*) [node]
11: 0x1427079  [node]
Aborted (core dumped)
❌ Error building UI:
Messages:
info  - Using webpack 5. Reason: future.webpack5 option enabled https://nextjs.org/docs/messages/webpack5
info  - Checking validity of types...
info  - Creating an optimized production build...
Errors:
<--- Last few GCs --->

[1250:0x60b89c0]   367128 ms: Scavenge (reduce) 982.8 (998.3) -> 982.1 (998.3) MB, 5.8 / 0.0 ms  (average mu = 0.165, current mu = 0.038) allocation failure
[1250:0x60b89c0]   367171 ms: Scavenge (reduce) 983.0 (995.3) -> 982.4 (996.3) MB, 6.1 / 0.0 ms  (average mu = 0.165, current mu = 0.038) allocation failure
[1250:0x60b89c0]   367205 ms: Scavenge (reduce) 983.1 (995.3) -> 982.6 (996.6) MB, 7.2 / 0.0 ms  (average mu = 0.165, current mu = 0.038) allocation failure


<--- JS stacktrace --->

FATAL ERROR: Ineffective mark-compacts near heap limit Allocation failed - JavaScript heap out of memory
 1: 0xa24ed0 node::Abort() [node]
 2: 0x966115 node::FatalError(char const*, char const*) [node]
 3: 0xb9acde v8::Utils::ReportOOMFailure(v8::internal::Isolate*, char const*, bool) [node]
 4: 0xb9b057 v8::internal::V8::FatalProcessOutOfMemory(v8::internal::Isolate*, char const*, bool) [node]
 5: 0xd56ea5  [node]
 6: 0xd57a2f  [node]
 7: 0xd65abb v8::internal::Heap::CollectGarbage(v8::internal::AllocationSpace, v8::internal::GarbageCollectionReason, v8::GCCallbackFlags) [node]
 8: 0xd6967c v8::internal::Heap::AllocateRawWithRetryOrFailSlowPath(int, v8::internal::AllocationType, v8::internal::AllocationOrigin, v8::internal::AllocationAlignment) [node]
 9: 0xd37d2b v8::internal::Factory::NewFillerObject(int, bool, v8::internal::AllocationType, v8::internal::AllocationOrigin) [node]
10: 0x108035f v8::internal::Runtime_AllocateInYoungGeneration(int, unsigned long*, v8::internal::Isolate*) [node]
11: 0x1427079  [node]
Aborted (core dumped)
untangledtech@lg:~$

**Comment by thatmattlove** [comment]
Almost certainly related to your system's resources. See [here](https://hyperglass.dev/docs/production), you'll likely need at least 2GB RAM to get through the UI build process.

**Comment by GrandArcher** [comment]
I added more CPUs and more RAM so now there are 4CPUs and 2G of ram but same thing happened even with setting the timeout to 1000 seconds.


| Metric | Value |
| :----- | :---- |
| **hyperglass Version** | 1.0.4 |
| **hyperglass Path** | `/home/untangledtech/hyperglass` |
| **Python Version** | `3.8.10` |
| **Node Version** | `14.17.2` |
| **Platform Info** | `Linux-5.4.0-80-generic-x86_64-with-glibc2.29` |
| **CPU Info** | Intel(R) Atom(TM) CPU  C2758  @ 2.41GHz |
| **Logical Cores** | `4` |
| **Physical Cores** | `4` |
| **Processor Speed** | `2.416666GHz` |
| **Total Memory** | 2.08 GB |
| **Memory Utilization** | 20.2% |
| **Total Disk Space** | 16.84 GB |
| **Disk Utilization** | 47.0% |

**Comment by thatmattlove** [comment]
> JavaScript heap out of memory

You may need more than 2GB. There’s no exact recipe, and sadly I don’t have much control over this particular step in the build process. You may also need to increase the JS heap, which I believe you can do by adding something like this to your environment variables:

```bash
export NODE_OPTIONS=--max_old_space_size=4096
```
