### ISSUE TITLE
Feature:  Kubernetes & Helm chart

### ISSUE THREAD

**Issue by samip5** [thatmattlove/hyperglass#157]
# Feature Description

After PR #149 is merged, there should be some traction on wanting an Helm chart for k8s deployment.

### Is your feature request related to a problem? Please describe.

Not really at this time

# Environment & Use Case

Environment is an k8s cluster running on Raspberry Pi's with one AMD64 worker.
Kubernetes is getting more and more popular, and this would help people using Hyperglass as well if it could be installed onto an k8s cluster quite easilly.

# Additional Context

https://phoenixnap.com/kb/what-is-helm

**Comment by thatmattlove** [comment]
I can see this (maybe) being valuable to _huge_ organizations using hyperglass (I'm not aware of any) at such a massive scale that they've exceeded the capacity a traditional approach can offer. If this is something the community would collectively benefit from, I would welcome a PR that implements a helm package for hyperglass _with testing_, from a maintainer that's willing to keep up with any future updates/issues.
