### ISSUE TITLE
Bird2 Support for VRF tables

### ISSUE THREAD

**Issue by guyaevans** [thatmattlove/hyperglass#158]
Bird2 now splits out seperate tables for IPv4 and IPv6. Named by default master4 and master6

It would be great if we could define the default VRF for each protocol. As currently only one table can be default. 

Thanks for a great project

**Comment by thatmattlove** [comment]
I'm not sure I follow. Are you saying we need to adjust the [default commands for BIRD](https://github.com/thatmattlove/hyperglass/blob/main/hyperglass/models/commands/bird.py), or that you need a way to customize the commands beyond [what's already available](https://hyperglass.dev/docs/commands)?

**Comment by guyaevans** [comment]
It would be nice to be able link two VRF tables (ie only display 1) as
bird2 has two seperate tables for IPv4 and IPv6--
Cordialement,
Kind Regards,

*Guy Evans*

**Comment by thatmattlove** [comment]
I _think_ I understand what you mean. This should be easily doable when #110 is implemented, which is currently underway (v2.0.0 branch). I'll mark this as blocked for now.
