### ISSUE TITLE
Comment Field

### ISSUE THREAD

**Issue by jakeb91** [thatmattlove/hyperglass#160]
# Feature Description

Enable the display of a comment field that can be presented on the GUI, for the end-user to type into (or select from a series of canned/pre-filled comments) as part of their query if they wish - able to be enabled/disabled as-well. My thoughts are that this field would simply be recorded in the logs (eg. a Comment field would then end up in the HTTP log messages sent to Slack, for example).

### Is your feature request related to a problem? Please describe.

Not related to a problem.

# Environment & Use Case

In an ISP environment, it can be common for more savvy end-users to use Looking Glass tools as part of trouble-shooting a perceived issue. Often these queries come from users of external networks that may be experiencing connectivity problems to service(s) hosted in that ISP network, and if there was an opportunity for someone to drop a comment about why they're using that particular Looking Glass it could be helpful in terms of catching a potentially odd problem. Essentially, being able to add a field that asks "What brings you here?" or similar could be useful.

Really just spitballing here - on one hand it seems like an easy addition - on the other I can see why people would vote against the feature ("Why can't they just email NOC / Support?").

**Comment by forkwhilefork** [comment]
As a customer I would never use this (wouldn't expect anyone to care what I wrote). As an operator, I would never look at this (would rather get a real ticket).

**Comment by thatmattlove** [comment]
I'm going to have to agree with @forkwhilefork here, I can't imagine a good reason to implement this, and I can think of lots of things that could go wrong. Pretty much all organizations will have a support process, and this would provide a way around it. Not to mention the security risks of having unvalidated user-input being sent to arbitrary systems. I think a perfectly fair middle-ground solution would be to use the [Links feature](https://hyperglass.dev/docs/ui/configuration#links) and provide an external link to a support form, or something along those lines.
