### ISSUE TITLE
URL's for speed test files

### ISSUE THREAD

**Issue by qwsj** [thatmattlove/hyperglass#161]
# Feature Description

URL's for speed test files.

### Is your feature request related to a problem? Please describe.

Maybe it resolve if you add additional block for URL with speed test files, or add providing URL when choosing a location in 'Command Customization'.

# Additional Context

Now we are making a markdown file for menus in footer with URL's but it not user-friendly and not noticeable.

**Comment by thatmattlove** [comment]
This has been brought up before (#134), and I [still believe this is out of scope for hyperglass](https://github.com/thatmattlove/hyperglass/issues/134#issuecomment-825373614).
