### ISSUE TITLE
'Human-readable' BGP communities

### ISSUE THREAD

**Issue by ggidofalvy-tc** [thatmattlove/hyperglass#173]
# Feature Description
I would very much like to see the ability to map BGP communities to human-readable strings, then seeing the BGP communities show up with the human-readable format alongside them. This feature request specifically applies to the structured output, as Hyperglass actually parses up the communities attached to the resulting routes. 

### Is your feature request related to a problem? Please describe.

As the user of a BGP looking glass, I might use it to check what sort of communities are set on specific routes, for example, when troubleshooting why traffic takes a given path (but not another). At the moment, the BGP communities list in the output can be difficult to parse up/comprehend, especially if the network in question uses a lot of distinct BGP communities for traffic engineering.

# Environment & Use Case
I would use this in an environment with network equipment that supports the structured output.

# Additional Context

**Comment by forkwhilefork** [comment]
I second this - I have a script that queries my routers and replaces the communities with human-readable text. I would like to extend this ability to my customers, too.
