### ISSUE TITLE
Possibility to run two instances of the application on one server

### ISSUE THREAD

**Issue by Ciacho** [thatmattlove/hyperglass#175]
# Feature Description

I wanted to run two instances of the application on one server, on two different local users (prod and preprod environment).
While I can easily install a python script (pip3 install hyperglass on two accounts - the files are in $ HOME / .local / lib / python3.7 / site-packages /), unfortunately it is impossible to run two processes.

### Is your feature request related to a problem? Please describe.

The first problem is the .json file which is in /tmp/hyperglass.env.json by default - the path is statically used in several files.
After manually changing it works, you can start the process and the GUI works.

./hyperglass/util/frontend.py:    env_file = Path("/tmp/preprhyperglass.env.json")  # noqa: S108
./hyperglass/util/__init__.py:    env_file = Path("/tmp/preprhyperglass.env.json")  # noqa: S108
./hyperglass/ui/nextdev.js:const envVars = require('/tmp/preprhyperglass.env.json');
./hyperglass/ui/next.config.js:const envVars = require('/tmp/preprhyperglass.env.json');

# Environment & Use Case

```
preprhyper@:~$ hyperglass system-info
❕ Please copy & paste this table in your bug report:

| Metric | Value |
| :----- | :---- |
| **hyperglass Version** | 1.0.4 |
| **hyperglass Path** | `/home/preprhyper/hyperglass` |
| **Python Version** | `3.7.3` |
| **Node Version** | `14.18.1` |
| **Platform Info** | `Linux-4.19.0-17-amd64-x86_64-with-debian-10.11` |
| **CPU Info** | Intel(R) Xeon(R) Gold 6230R CPU @ 2.10GHz |
| **Logical Cores** | `2` |
| **Physical Cores** | `2` |
| **Processor Speed** | `2.1GHz` |
| **Total Memory** | 4.11 GB |
| **Memory Utilization** | 19.4% |
| **Total Disk Space** | 21.0 GB |
| **Disk Utilization** | 30.6% |
```

# Additional Context

**Comment by thatmattlove** [comment]
Hello, I've implemented this in 2.0, which is in the final stages of development. Essentially, `/tmp/hyperglass.env.json` is no longer used and any pertinent details it used to contain are generated within the `ui` directory of the hyperglass library files. So, running two instances of hyperglass on the same system **but in different virtual environments** should work now.
