### ISSUE TITLE
Traceroute - Toggle Resolving Hostnames

### ISSUE THREAD

**Issue by booth-f** [thatmattlove/hyperglass#208]
# Feature Description

Toggle feature for DNS resolution of remote router addresses in traceroute for Bird-based devices.

### Is your feature request related to a problem? Please describe.

Yes,

I have a Hyperglass server running in my network and whenever I run a traceroute from a few servers I get an error message saying "Error connecting to $HOST: No response." or Request timed out. Pasting the command Hyperglass generates in debug mode sent to the server shows DNS resolutions time out on certain hosts that don't have reverse records available which causes the traceroute program to stop and for Hyperglass to fail with a communications error message.

This same command modified with -n (eg: traceroute -6 -n .....) completes quickly without issue. Unfortunately I tried to see what was required to make this simple one-off modification for all my traceroute commands but quickly discovered I'd have to overwrite and re-write all the commands for the rest of the looking glass commands to do so.

# Environment & Use Case

Networks where traceroute defaults to trying to resolve the system hostnames from the reverse records and not all hosts in the network have reverse records attached.

# Additional Context

I figure there can be situations where people want to have the ability to toggle hostname resolutions in their traceroutes but probably good to have this as a default to "off" to avoid issues like this.

**Comment by thatmattlove** [comment]
Note: I am referencing [v2.0.0](https://github.com/thatmattlove/hyperglass/tree/v2.0.0) which may be different than what you were originally using (though the result is likely the same).

In v2.0.0, the concept of [directives](https://v2.hyperglass.dev/configuration/directives) were introduced, which allows you to add your own (or override built-in) directives/commands. I think this would be the best solution to your request, as a feature switch for a specific directive type would be difficult to implement. I don't think disabling DNS resolution by default is the way to go either - I know many users find the DNS resolution to be valuable when using a looking glass.
