### ISSUE TITLE
VRF name changed when using multiple VRFs

### ISSUE THREAD

**Issue by ServerForge** [thatmattlove/hyperglass#212]
# Bug Description
When you define multiple VRFs for a single router you get a selector on the page to choose the route table, However it appears to change the VRF name so only the first letter is capaitalized causing the "VRF <name> is not defined." Error because it has changed the name. 

# Expected behavior

The VRF name should not be altered from what is defined in the config file. 

# Steps to Reproduce

Setup multiple routers with multiple and overlapping VRFs. 
## Local Configurations

  - name: Hampton, VA-1
    address: 2a0e:b100:107::101
    network:
      name: production
      display_name: AS207556
    credential:
      username: redacted
      key: redacted
    port: 22
    nos: linux
    vrfs:
      - name: AS207556
        ipv4:
          source_address: 23.136.232.26
        ipv6:
          source_address: 2a0e:b100:107::101
      - name: AS23428
        ipv4: null
        ipv6:
          source_address: 2602:fb68:c0::0
## Logs

```
<logs>
```

# Possible Solution

# Environment

## Server
| Metric | Value |
| :----- | :---- |
| **hyperglass Version** | 1.0.4 |
| **hyperglass Path** | `/etc/hyperglass` |
| **Python Version** | `3.7.13` |
| **Node Version** | `14.19.1` |
| **Platform Info** | `Linux-5.15.0-43-generic-x86_64-with-Ubuntu-22.04-jammy` |
| **CPU Info** | Common KVM processor |
| **Logical Cores** | `16` |
| **Physical Cores** | `16` |
| **Processor Speed** | `2.493988GHz` |
| **Total Memory** | 8.33 GB |
| **Memory Utilization** | 16.3% |
| **Total Disk Space** | 134.68 GB |
| **Disk Utilization** | 8.6% |

## Client

- OS & Version: Windows 11
- Browser: Chrome

### Smartphone Details (if applicable)

- Device: 
- OS: 
- Browser:

**Comment by BouchardClaude** [comment]
I have the same bug, it look like - are change to _ , and uppercase and converted to lowercase, making it not working in many case?
