### ISSUE TITLE
BGP route query fails due to whois to bgp.tools.

### ISSUE THREAD

**Issue by iskandarbasman** [thatmattlove/hyperglass#225]
# Bug Description

BGP route query fails due to whois to bgp.tools.
[DEBUG] 20230830 17:07:12 | hyperglass.external.bgptools:100 | run_whois_sync → Opening connection to bgp.tools

Can I disable this function for hyperglass for the BGP Route lookup ?

-
Do not see the purpose of the this whois lookup which is send our query information to bgp.tools.
```
[DEBUG] 20230831 13:02:42 | hyperglass.external.bgptools:100 | run_whois_sync → Opening connection to bgp.tools
[DEBUG] 20230831 13:02:42 | hyperglass.external.bgptools:113 | run_whois_sync → Closing connection to bgp.tools
[DEBUG] 20230831 13:02:42 | hyperglass.external.bgptools:59 | parse_whois → Parsed bgp.tools data: {'8.8.8.8': {'asn': '15169', 'ip': '8.8.8.8', 'prefix': '8.8.8.0/24', 'country': 'US', 'rir': 'ARIN', 'allocated': '2000-03-30', 'org': 'Google LLC'}}
```

**Comment by henriklb** [comment]
set force_cidr to false

**Comment by iskandarbasman** [comment]
> set force_cidr to false

Thanks for the tip.
Not sure how I missed this thanks ! It works.

https://hyperglass.dev/docs/parameters
![image](https://github.com/thatmattlove/hyperglass/assets/67727557/c0e7abc3-ebe8-4d12-85a9-61a61582f572)


[DEBUG] 20230923 00:59:15 | hyperglass.models.api.validators:24 | _member_of → Checking membership of 3.115.153.86/32 for 10.0.0.0/8
[DEBUG] 20230923 00:59:15 | hyperglass.models.api.validators:24 | _member_of → Checking membership of 3.115.153.86/32 for 0.0.0.0/0
[DEBUG] 20230923 00:59:15 | hyperglass.models.api.validators:31 | _member_of → 3.115.153.86/32 is a member of 0.0.0.0/0
[DEBUG] 20230923 00:59:15 | hyperglass.models.api.validators:109 | validate_ip → 3.115.153.86/32 is allowed by access-list AccessList4(network=IPv4Network('0.0.0.0/0'), action='permit', ge=0, le=32)
[DEBUG] 20230923 00:59:15 | hyperglass.models.api.validators:180 | validate_ip → Validation passed for 3.115.153.86
[DEBUG] 20230923 00:59:15 | hyperglass.api.routes:80 | query → Initialized cache HyperglassCache(db=1, host=localhost, port=6379, password=None)
[DEBUG] 20230923 00:59:15 | hyperglass.api.routes:89 | query → Cache Timeout: 120
