### ISSUE TITLE
very poor documentation, and everything depreciated.

### ISSUE THREAD

**Issue by SavaletDev** [thatmattlove/hyperglass#227]
I've been trying to install hyperglass for 2 days now, but between the out-of-date script, which I had to install again using pip, which crashes, and now the build, which is impossible to launch because nothing is explained properly, you'll have to improve.

**Comment by thatmattlove** [comment]
Sorry for your troubles, but perhaps you missed the note on the main readme:

> Unfortunately, I've been extremely busy in my work and personal life and haven't had a lot of time to dedicate to hyperglass recently. I'm hoping that will change soon, but in the meantime, hyperglass v1.0.0 might be unusable or unstable unless you're running Ubuntu 18.04, Python 3.6, and Node 14, which is probably a bad idea for security reasons. v2.0.0 is almost ready for release, but not quite yet.
