### ISSUE TITLE
hyperglass logo not shown in firefox 

### ISSUE THREAD

**Issue by henriklb** [thatmattlove/hyperglass#229]
# Bug Description
The hyperglass logo (top centered logo) is not shown in firefox 115.0.2. It works fine in chrome and edge.

# Steps to Reproduce
1. Go to https://demo.hyperglass.dev/ using Firefox 115.0.2 on Desktop
2. Observe the lack of hyperglass logo (top centered logo) 

## Local Configurations
None. See https://demo.hyperglass.dev/ 

# Environment
Windows 10, firefox 115.0.2 on Desktop

**Comment by henriklb** [comment]
Appear to be an issue specifict to .svg images. png-files works fine

**Comment by dkay-zaxxx** [comment]
I think it just a problem with the svg loaded on that specific demo. It works just fine on my instance
