### ISSUE TITLE
Ubuntu 22.04.3 LTS New Install Failure

### ISSUE THREAD

**Issue by Gronkstar** [thatmattlove/hyperglass#231]
Welcome to Ubuntu 22.04.3 LTS (GNU/Linux 5.15.0-84-generic x86_64)

$ pip3 install hyperglass
Defaulting to user installation because normal site-packages is not writeable
Collecting hyperglass
  Using cached hyperglass-1.0.4-py3-none-any.whl (428 kB)
Collecting uvloop<0.15.0,>=0.14.0
  Using cached uvloop-0.14.0.tar.gz (2.0 MB)
  Preparing metadata (setup.py) ... done
Collecting uvicorn[standard]<0.14.0,>=0.13.4
  Using cached uvicorn-0.13.4-py3-none-any.whl (46 kB)
Requirement already satisfied: distro<2.0.0,>=1.5.0 in /usr/lib/python3/dist-packages (from hyperglass) (1.7.0)
Collecting scrapli[asyncssh]<2022.0.0,>=2021.1.30
  Using cached scrapli-2021.7.30-py3-none-any.whl (128 kB)
Collecting cryptography==3.0.0
  Using cached cryptography-3.0-cp35-abi3-manylinux2010_x86_64.whl (2.7 MB)
Requirement already satisfied: PyJWT<3.0.0,>=2.0.1 in /usr/lib/python3/dist-packages (from hyperglass) (2.3.0)
Collecting py-cpuinfo<8.0.0,>=7.0.0
  Using cached py-cpuinfo-7.0.0.tar.gz (95 kB)
  Preparing metadata (setup.py) ... done
Collecting favicons<0.0.10,>=0.0.9
  Using cached favicons-0.0.9-py3-none-any.whl (13 kB)
Collecting xmltodict<0.13.0,>=0.12.0
  Using cached xmltodict-0.12.0-py2.py3-none-any.whl (9.2 kB)
Collecting aredis<2.0.0,>=1.1.8
  Using cached aredis-1.1.8.tar.gz (128 kB)
  Preparing metadata (setup.py) ... done
Collecting aiofiles<0.7.0,>=0.6.0
  Using cached aiofiles-0.6.0-py3-none-any.whl (11 kB)
Collecting redis<4.0.0,>=3.5.3
  Using cached redis-3.5.3-py2.py3-none-any.whl (72 kB)
Collecting netmiko<4.0.0,>=3.4.0
  Using cached netmiko-3.4.0-py3-none-any.whl (178 kB)
Collecting httpx<0.18.0,>=0.17.1
  Using cached httpx-0.17.1-py3-none-any.whl (68 kB)
Collecting pydantic<2.0.0,>=1.8.1
  Using cached pydantic-1.10.13-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (3.1 MB)
Requirement already satisfied: PyYAML<6.0.0,>=5.4.1 in /usr/lib/python3/dist-packages (from hyperglass) (5.4.1)
Collecting paramiko<3.0.0,>=2.7.2
  Using cached paramiko-2.12.0-py2.py3-none-any.whl (213 kB)
Collecting psutil<6.0.0,>=5.7.2
  Using cached psutil-5.9.5-cp36-abi3-manylinux_2_12_x86_64.manylinux2010_x86_64.manylinux_2_17_x86_64.manylinux2014_x86_64.whl (282 kB)
Collecting Pillow<8.0,>=7.2
  Using cached Pillow-7.2.0.tar.gz (39.1 MB)
  Preparing metadata (setup.py) ... done
Collecting gunicorn<21.0.0,>=20.1.0
  Using cached gunicorn-20.1.0-py3-none-any.whl (79 kB)
Collecting inquirer<3.0.0,>=2.6.3
  Using cached inquirer-2.10.1-py3-none-any.whl (17 kB)
Collecting click<8.0.0,>=7.1.2
  Using cached click-7.1.2-py2.py3-none-any.whl (82 kB)
Collecting loguru<0.6.0,>=0.5.3
  Using cached loguru-0.5.3-py3-none-any.whl (57 kB)
Collecting fastapi<0.64.0,>=0.63.0
  Using cached fastapi-0.63.0-py3-none-any.whl (50 kB)
Requirement already satisfied: six>=1.4.1 in /usr/lib/python3/dist-packages (from cryptography==3.0.0->hyperglass) (1.16.0)
Collecting cffi!=1.11.3,>=1.8
  Using cached cffi-1.16.0-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (443 kB)
Collecting starlette==0.13.6
  Using cached starlette-0.13.6-py3-none-any.whl (59 kB)
Collecting svglib<2.0.0,>=1.0.0
  Using cached svglib-1.5.1.tar.gz (913 kB)
  Preparing metadata (setup.py) ... done
Collecting rich<9.0,>=6.0
  Using cached rich-8.0.0-py3-none-any.whl (155 kB)
Collecting typer<0.4.0,>=0.3.1
  Using cached typer-0.3.2-py3-none-any.whl (21 kB)
Requirement already satisfied: setuptools>=3.0 in /usr/lib/python3/dist-packages (from gunicorn<21.0.0,>=20.1.0->hyperglass) (59.6.0)
Collecting httpcore<0.13,>=0.12.1
  Using cached httpcore-0.12.3-py3-none-any.whl (55 kB)
Requirement already satisfied: certifi in /usr/lib/python3/dist-packages (from httpx<0.18.0,>=0.17.1->hyperglass) (2020.6.20)
Collecting sniffio
  Using cached sniffio-1.3.0-py3-none-any.whl (10 kB)
Collecting rfc3986[idna2008]<2,>=1.3
  Using cached rfc3986-1.5.0-py2.py3-none-any.whl (31 kB)
Collecting python-editor>=1.0.4
  Using cached python_editor-1.0.4-py3-none-any.whl (4.9 kB)
Collecting readchar>=3.0.6
  Using cached readchar-4.0.5-py3-none-any.whl (8.5 kB)
Collecting blessed>=1.19.0
  Using cached blessed-1.20.0-py2.py3-none-any.whl (58 kB)
Collecting scp>=0.13.2
  Using cached scp-0.14.5-py2.py3-none-any.whl (8.7 kB)
Collecting ntc-templates
  Using cached ntc_templates-3.5.0-py3-none-any.whl (379 kB)
Collecting tenacity
  Using cached tenacity-8.2.3-py3-none-any.whl (24 kB)
Requirement already satisfied: pyserial in /usr/lib/python3/dist-packages (from netmiko<4.0.0,>=3.4.0->hyperglass) (3.5)
Collecting pynacl>=1.0.1
  Using cached PyNaCl-1.5.0-cp36-abi3-manylinux_2_17_x86_64.manylinux2014_x86_64.manylinux_2_24_x86_64.whl (856 kB)
Requirement already satisfied: bcrypt>=3.1.3 in /usr/lib/python3/dist-packages (from paramiko<3.0.0,>=2.7.2->hyperglass) (3.2.0)
Collecting typing-extensions>=4.2.0
  Using cached typing_extensions-4.8.0-py3-none-any.whl (31 kB)
Collecting asyncssh<3.0.0,>=2.2.1
  Using cached asyncssh-2.14.0-py3-none-any.whl (351 kB)
Collecting h11>=0.8
  Using cached h11-0.14.0-py3-none-any.whl (58 kB)
Collecting watchgod>=0.6
  Using cached watchgod-0.8.2-py3-none-any.whl (12 kB)
Collecting httptools==0.1.*
  Using cached httptools-0.1.2.tar.gz (106 kB)
  Preparing metadata (setup.py) ... done
Collecting websockets==8.*
  Using cached websockets-8.1.tar.gz (58 kB)
  Preparing metadata (setup.py) ... done
Collecting python-dotenv>=0.13
  Using cached python_dotenv-1.0.0-py3-none-any.whl (19 kB)
Collecting asyncssh<3.0.0,>=2.2.1
  Using cached asyncssh-2.13.2-py3-none-any.whl (349 kB)
  Using cached asyncssh-2.13.1-py3-none-any.whl (348 kB)
  Using cached asyncssh-2.13.0-py3-none-any.whl (348 kB)
  Using cached asyncssh-2.12.0-py3-none-any.whl (346 kB)
  Using cached asyncssh-2.11.0-py3-none-any.whl (343 kB)
  Using cached asyncssh-2.10.1-py3-none-any.whl (335 kB)
  Using cached asyncssh-2.10.0-py3-none-any.whl (335 kB)
Collecting wcwidth>=0.1.4
  Using cached wcwidth-0.2.8-py2.py3-none-any.whl (31 kB)
Collecting pycparser
  Using cached pycparser-2.21-py2.py3-none-any.whl (118 kB)
Requirement already satisfied: idna in /usr/lib/python3/dist-packages (from rfc3986[idna2008]<2,>=1.3->httpx<0.18.0,>=0.17.1->hyperglass) (3.3)
Requirement already satisfied: colorama<0.5.0,>=0.4.0 in /usr/lib/python3/dist-packages (from rich<9.0,>=6.0->favicons<0.0.10,>=0.0.9->hyperglass) (0.4.4)
Collecting pygments<3.0.0,>=2.6.0
  Using cached Pygments-2.16.1-py3-none-any.whl (1.2 MB)
Collecting commonmark<0.10.0,>=0.9.0
  Downloading commonmark-0.9.1-py2.py3-none-any.whl (51 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 51.1/51.1 KB 1.6 MB/s eta 0:00:00
Collecting rich<9.0,>=6.0
  Using cached rich-7.1.0-py3-none-any.whl (153 kB)
  Using cached rich-7.0.0-py3-none-any.whl (151 kB)
  Using cached rich-6.2.0-py3-none-any.whl (150 kB)
  Using cached rich-6.1.2-py3-none-any.whl (149 kB)
  Using cached rich-6.1.1-py3-none-any.whl (149 kB)
  Using cached rich-6.1.0-py3-none-any.whl (149 kB)
  Using cached rich-6.0.0-py3-none-any.whl (146 kB)
INFO: pip is looking at multiple versions of rfc3986[idna2008] to determine which version is compatible with other requirements. This could take a while.
Collecting rfc3986[idna2008]<2,>=1.3
  Using cached rfc3986-1.4.0-py2.py3-none-any.whl (31 kB)
INFO: pip is looking at multiple versions of readchar to determine which version is compatible with other requirements. This could take a while.
Collecting readchar>=3.0.6
  Using cached readchar-4.0.4-py3-none-any.whl (8.5 kB)
INFO: pip is looking at multiple versions of python-editor to determine which version is compatible with other requirements. This could take a while.
INFO: pip is looking at multiple versions of python-dotenv to determine which version is compatible with other requirements. This could take a while.
Collecting python-dotenv>=0.13
  Using cached python_dotenv-0.21.1-py3-none-any.whl (19 kB)
INFO: pip is looking at multiple versions of pynacl to determine which version is compatible with other requirements. This could take a while.
Collecting pynacl>=1.0.1
  Using cached PyNaCl-1.4.0-cp35-abi3-manylinux1_x86_64.whl (961 kB)
INFO: pip is looking at multiple versions of sniffio to determine which version is compatible with other requirements. This could take a while.
Collecting sniffio
  Using cached sniffio-1.2.0-py3-none-any.whl (10 kB)
  Using cached sniffio-1.1.0-py3-none-any.whl (4.5 kB)
  Using cached sniffio-1.0.0-py3-none-any.whl (4.4 kB)
INFO: pip is looking at multiple versions of httpcore to determine which version is compatible with other requirements. This could take a while.
Collecting httpcore<0.13,>=0.12.1
  Using cached httpcore-0.12.2-py3-none-any.whl (54 kB)
INFO: pip is looking at multiple versions of h11 to determine which version is compatible with other requirements. This could take a while.
Collecting h11>=0.8
  Using cached h11-0.13.0-py3-none-any.whl (58 kB)
INFO: pip is looking at multiple versions of cffi to determine which version is compatible with other requirements. This could take a while.
Collecting cffi!=1.11.3,>=1.8
  Using cached cffi-1.15.1-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (441 kB)
INFO: pip is looking at multiple versions of blessed to determine which version is compatible with other requirements. This could take a while.
Collecting blessed>=1.19.0
  Using cached blessed-1.19.1-py2.py3-none-any.whl (58 kB)
INFO: pip is looking at multiple versions of bcrypt to determine which version is compatible with other requirements. This could take a while.
Collecting bcrypt>=3.1.3
  Using cached bcrypt-4.0.1-cp36-abi3-manylinux_2_28_x86_64.whl (593 kB)
INFO: pip is looking at multiple versions of asyncssh to determine which version is compatible with other requirements. This could take a while.
Collecting asyncssh<3.0.0,>=2.2.1
  Using cached asyncssh-2.9.0-py3-none-any.whl (334 kB)
  Using cached asyncssh-2.8.1-py3-none-any.whl (287 kB)
INFO: pip is looking at multiple versions of xmltodict to determine which version is compatible with other requirements. This could take a while.
INFO: pip is looking at multiple versions of uvloop to determine which version is compatible with other requirements. This could take a while.
INFO: pip is looking at multiple versions of websockets to determine which version is compatible with other requirements. This could take a while.
Collecting websockets==8.*
  Using cached websockets-8.0.2.tar.gz (57 kB)
  Preparing metadata (setup.py) ... done
  Using cached websockets-8.0.1.tar.gz (57 kB)
  Preparing metadata (setup.py) ... done
  Using cached websockets-8.0.tar.gz (57 kB)
  Preparing metadata (setup.py) ... done
INFO: pip is looking at multiple versions of httptools to determine which version is compatible with other requirements. This could take a while.
Collecting httptools==0.1.*
  Using cached httptools-0.1.1.tar.gz (106 kB)
  Preparing metadata (setup.py) ... done
INFO: pip is looking at multiple versions of websockets to determine which version is compatible with other requirements. This could take a while.
  Using cached httptools-0.1.0.tar.gz (106 kB)
  Preparing metadata (setup.py) ... done
INFO: pip is looking at multiple versions of uvicorn[standard] to determine which version is compatible with other requirements. This could take a while.
INFO: pip is looking at multiple versions of scrapli[asyncssh] to determine which version is compatible with other requirements. This could take a while.
Collecting scrapli[asyncssh]<2022.0.0,>=2021.1.30
  Using cached scrapli-2021.1.30-py3-none-any.whl (192 kB)
INFO: pip is looking at multiple versions of redis to determine which version is compatible with other requirements. This could take a while.
INFO: pip is looking at multiple versions of pyyaml to determine which version is compatible with other requirements. This could take a while.
Collecting PyYAML<6.0.0,>=5.4.1
  Using cached PyYAML-5.4.1.tar.gz (175 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... error
  error: subprocess-exited-with-error

  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> [43 lines of output]
      running egg_info
      Traceback (most recent call last):
        File "/usr/lib/python3/dist-packages/pip/_vendor/pep517/in_process/_in_process.py", line 363, in <module>
          main()
        File "/usr/lib/python3/dist-packages/pip/_vendor/pep517/in_process/_in_process.py", line 345, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
        File "/usr/lib/python3/dist-packages/pip/_vendor/pep517/in_process/_in_process.py", line 130, in get_requires_for_build_wheel
          return hook(config_settings)
        File "/usr/lib/python3/dist-packages/setuptools/build_meta.py", line 162, in get_requires_for_build_wheel
          return self._get_build_requires(
        File "/usr/lib/python3/dist-packages/setuptools/build_meta.py", line 143, in _get_build_requires
          self.run_setup()
        File "/usr/lib/python3/dist-packages/setuptools/build_meta.py", line 158, in run_setup
          exec(compile(code, __file__, 'exec'), locals())
        File "setup.py", line 271, in <module>
          setup(
        File "/usr/lib/python3/dist-packages/setuptools/__init__.py", line 153, in setup
          return distutils.core.setup(**attrs)
        File "/usr/lib/python3/dist-packages/setuptools/_distutils/core.py", line 148, in setup
          return run_commands(dist)
        File "/usr/lib/python3/dist-packages/setuptools/_distutils/core.py", line 163, in run_commands
          dist.run_commands()
        File "/usr/lib/python3/dist-packages/setuptools/_distutils/dist.py", line 967, in run_commands
          self.run_command(cmd)
        File "/usr/lib/python3/dist-packages/setuptools/_distutils/dist.py", line 986, in run_command
          cmd_obj.run()
        File "/usr/lib/python3/dist-packages/setuptools/command/egg_info.py", line 299, in run
          self.find_sources()
        File "/usr/lib/python3/dist-packages/setuptools/command/egg_info.py", line 306, in find_sources
          mm.run()
        File "/usr/lib/python3/dist-packages/setuptools/command/egg_info.py", line 541, in run
          self.add_defaults()
        File "/usr/lib/python3/dist-packages/setuptools/command/egg_info.py", line 578, in add_defaults
          sdist.add_defaults(self)
        File "/usr/lib/python3/dist-packages/setuptools/_distutils/command/sdist.py", line 228, in add_defaults
          self._add_defaults_ext()
        File "/usr/lib/python3/dist-packages/setuptools/_distutils/command/sdist.py", line 312, in _add_defaults_ext
          self.filelist.extend(build_ext.get_source_files())
        File "setup.py", line 201, in get_source_files
          self.cython_sources(ext.sources, ext)
        File "/usr/lib/python3/dist-packages/setuptools/_distutils/cmd.py", line 103, in __getattr__
          raise AttributeError(attr)
      AttributeError: cython_sources
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× Getting requirements to build wheel did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.

**Comment by xfy777** [comment]
Second this, script fails and so does pip install

**Comment by DamonOnYT** [comment]
+1

**Comment by rouvelgh** [comment]
+1

**Comment by herzadigital** [comment]
+1

**Comment by baragoon** [comment]
+1
