### ISSUE TITLE
Debian 12 - Build-ui Fail

### ISSUE THREAD

**Issue by Kleiton-Silva** [thatmattlove/hyperglass#233]
![Captura de tela 2024-01-18 104608](https://github.com/thatmattlove/hyperglass/assets/143813585/81b76ac5-a798-4d81-8f93-3db64294bfc8)

**Comment by gondimcodes** [comment]
Same error here.

**Comment by Kleiton-Silva** [comment]
I'm don't fix this error, then I came back to Debian 11.
But now there a new bug, Hyperglass cann't connect do FRRouting to run the queries.
The vtysh works properly when I call it on terminal, but not when hyperglass do it.
