### ISSUE TITLE
Device quantity issue

### ISSUE THREAD

**Issue by KincaidYang** [thatmattlove/hyperglass#237]
Hi @thatmattlove , When the number of devices exceeds 5, the following error will be triggered, causing the build to fail:
![image](https://github.com/thatmattlove/hyperglass/assets/91786638/84c83eb1-6542-45e2-b385-b9eda0810215)
![image](https://github.com/thatmattlove/hyperglass/assets/91786638/ad46984b-77d8-4709-93f0-f9c7c52143d6)

**Comment by thatmattlove** [comment]
I've confirmed this in my development environment. Will start working on a fix.

**Comment by thatmattlove** [comment]
@KincaidYang this should be fixed in cea421c.
