### ISSUE TITLE
v2.0.0 Docker - How to use?

### ISSUE THREAD

**Issue by f0o** [thatmattlove/hyperglass#241]
Selected bug report because there is no general option;

I've built the docker-image in v2.0.0 branch but am unsure how to use it, any pointers?

**Comment by KincaidYang** [comment]
After a successful startup, you should be able to access it via http://serverip:8081.

**Comment by f0o** [comment]
did not know there's a V2 docs!Thanks a lot!On 1 Apr 2024 11:14, YANGJINZE ***@***.***> wrote:
See https://v2.hyperglass.dev/installation/docker && https://v2.hyperglass.dev/configuration/overview
