### ISSUE TITLE
bug: logo display

### ISSUE THREAD

**Issue by M0NsTeRRR** [thatmattlove/hyperglass#258]
# Bug Description
Logo should be centered on mobile.
Also it would be better if the logo can be resized automatically by hyperglass depending on the available size on top of "Location" title instead of letting user setting custom `width`.

![image](https://github.com/thatmattlove/hyperglass/assets/37785089/1143592d-b91a-458a-8729-702af23c8782)

**Comment by thatmattlove** [comment]
Centering will be included in 2.0.2.

> Also it would be better if the logo can be resized automatically by hyperglass depending on the available size on top of "Location" title instead of letting user setting custom width.

I tried this initially, but found that it was entirely too difficult to get right, because of the variety of logo sizes users have, hence the addition of the `width` option as a "last resort" to adjust your logo as needed.
